name: my_first_workflow

on: push

jobs: 
    myfirstjob:
    runs-on: ubuntu-latest
    steps: 

        - uses: actions/checkout@v4
        with:
        - name: print messege
           run: echo "print messege"

        - name: list and cat the files
           run: 
