name: Run C Program

on:
  workflow_dispatch:

jobs:
  Matrix-configuration:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update the environment
        run: sudo apt-get update

      - name: Compile C program
        run: gcc sample.c -o sample

      - name: Run C program (only on ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: ./sample
