name: Run C Program

on:
  #push
  workflow_dispatch:

jobs:
  # build-and-run:
  Matrix-configuration:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: update the environment
        run: sudo apt-get update 

      - name: Compile C program
        run: gcc sample.c -o sample

      - name: Run C program
        run: ./sample
