on: push

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repo
            uses: actions/checkout@v4.2.2

          - name: Welcome messege and list the files
            run: |
             echo "my demo workflow"
              ls
          
          - name: uploading the README.md file
            uses: actions/upload-artifact@v4
            with:
               name: README.md file
               path: README.md
          
          - name: Create sample.txt
            run: echo "Hello, world!" > sample.txt

          - name: Upload sample.txt
            uses: actions/upload-artifact@v4
            with:
               name: sample
               path: sample.txt
    
    Test:
        runs-on: ubuntu-latest
        needs: Build
        steps:

          - name: Download sample.txt
            uses: actions/download-artifact@v4
            with:
                name: sample

          - name: Display contents of sample.txt
            run: cat sample.txt

          - name: Second jobs starts
            run:  cat sample.txt
