on: push

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repo
            uses: actions/checkout@v4.2.2

          - name: Welcome messege and list the files
            run: |
             echo "my workflow"
              ls
    
    Test:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: Second jobs starts
              run: cat "README.md"
    
          
