on: push

jobs:
    myfirstjobs:
      runs-on: ubuntu-latest
      steps:
          - name: Welcome messege
            run: echo "my workflow"
          
          - name: list files
            run: ls
