on: push

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repo
            uses: actions/checkout@v4.2.2

          - name: Welcome messege and list the files
            run: |
             echo "my workflow"
              ls
          
          - name: uploading the README.md file
            uses: actions/upload-artifact@v4
            with:
               name: README.md file
               path: README.md
    
    Test:
        runs-on: ubuntu-latest
        needs: Build
        steps:

          - name: Downloading the README.md file
            uses: actions/download-artifact@v4
            with:
                name: Reading the file
                path: cat docs/README.md

          - name: Second jobs starts
            run:  cat docs/README.md
    
          
