name: Build Docker Image on Push

on: 
    #schedule:
    #   - cron: "*/1 * * * *"
    push

env:
  IMAGE_NAME: myapp
  IMAGE_TAG: latest

jobs:
  Docker-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: List Docker Images
        run: docker images

  Docker-Login:
    runs-on: ubuntu-latest
    needs: Docker-Build

    steps:
      - name: Docker login
        run: echo docker login --username= ${{vars.DOCKER_USERNAME}} --password= ${{secrets.DOCKER_PASSWORD}}

      - name: Docker run
        #timeout-minutes: 1
        run: | 
            echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
            sleep 10s