name: Secrets and variables

on: push

env: 
    CONTAINER_REGISTRY: https://app.docker.com/
    

jobs:   
    Docker-login:
        runs-on: ubuntu-latest
        steps:
            - name: Docker-Build
              run: echo docker build -t ${{env.CONTAINER_REGISTRY}}

            - name: Docker-login
              run: echo docker login --username= ${{vars.DOCKER_USERNAME}} --password= ${{secrets.DOCKER_PASSWORD}}

            - name: Display
              run:  docker images

