name: Build Docker Image on Push

on: 
  workflow_dispatch: 

env:
  IMAGE_NAME: myapp
  IMAGE_TAG: latest

jobs:
  Docker-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: List Docker Images
        run: docker images

  Docker-Login:
    runs-on: ubuntu-latest
    needs: Docker-Build

    steps:
      - name: Docker login
        run: echo docker login --username= ${{ vars.DOCKER_USERNAME }} --password= ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR login
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
            
      - name: container registry push
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: ghcr.io/${{github.repository_owner}}/demoworkflow:${{ github.sha }}
